"""Indice mestre de pacientes: candidatos a duplicata e rastro de unificacao

Revision ID: 1025765f67df
Revises: cad0b85b049d
Create Date: 2026-08-03 20:57:57.771961

Em escala nacional, a mesma pessoa e cadastrada em municipios diferentes — as
vezes so com CPF, as vezes so com CNS. Sem reconciliar isso, o prontuario
longitudinal nao existe.

`candidatos_duplicata` guarda a DECISAO sobre cada par, e nao apenas a suspeita:
sem isso, todo par ja analisado e considerado pessoas distintas voltaria na
varredura seguinte, e a fila de revisao viraria ruido que ninguem olha.

`pacientes.unificado_para_id` preserva o cadastro absorvido apontando para o
sobrevivente. Em prontuario, apagar e perder rastro.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1025765f67df'
down_revision = 'cad0b85b049d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos_duplicata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_menor_id', sa.Integer(), nullable=False),
    sa.Column('paciente_maior_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidencias', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sobrevivente_id', sa.Integer(), nullable=True),
    sa.Column('detectado_em', sa.DateTime(), nullable=False),
    sa.Column('decidido_em', sa.DateTime(), nullable=True),
    sa.Column('decidido_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decidido_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paciente_maior_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['paciente_menor_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['sobrevivente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_menor_id', 'paciente_maior_id', name='uq_candidato_par')
    )
    with op.batch_alter_table('candidatos_duplicata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidatos_duplicata_paciente_maior_id'), ['paciente_maior_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidatos_duplicata_paciente_menor_id'), ['paciente_menor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidatos_duplicata_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidatos_duplicata_status'), ['status'], unique=False)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unificado_para_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unificado_em', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pacientes_unificado_para_id'), ['unificado_para_id'], unique=False)
        # Constraint anonima quebra o modo batch do SQLite, que e como o
        # Alembic adiciona chave estrangeira num banco sem ALTER TABLE.
        batch_op.create_foreign_key('fk_pacientes_unificado_para_id_pacientes',
                                    'pacientes', ['unificado_para_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pacientes_unificado_para_id_pacientes',
                                 type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pacientes_unificado_para_id'))
        batch_op.drop_column('unificado_em')
        batch_op.drop_column('unificado_para_id')

    with op.batch_alter_table('candidatos_duplicata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidatos_duplicata_status'))
        batch_op.drop_index(batch_op.f('ix_candidatos_duplicata_score'))
        batch_op.drop_index(batch_op.f('ix_candidatos_duplicata_paciente_menor_id'))
        batch_op.drop_index(batch_op.f('ix_candidatos_duplicata_paciente_maior_id'))

    op.drop_table('candidatos_duplicata')
    # ### end Alembic commands ###
