"""Hierarquia territorial IBGE: municipios e vinculo da unidade

Revision ID: 5aad58eaed4b
Revises: 1025765f67df
Create Date: 2026-08-03 21:14:26.047419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aad58eaed4b'
down_revision = '1025765f67df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('codigo_ibge', sa.String(length=7), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('regional_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regional_id'], ['regionais.id'], ),
    sa.PrimaryKeyConstraint('codigo_ibge')
    )
    with op.batch_alter_table('municipios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_municipios_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipios_regional_id'), ['regional_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_municipios_uf'), ['uf'], unique=False)

    with op.batch_alter_table('unidades_saude', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipio_ibge', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('regional_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_unidades_saude_municipio_ibge'), ['municipio_ibge'], unique=False)
        batch_op.create_index(batch_op.f('ix_unidades_saude_regional_id'), ['regional_id'], unique=False)
        batch_op.create_foreign_key(None, 'regionais', ['regional_id'], ['id'])
        batch_op.create_foreign_key(None, 'municipios', ['municipio_ibge'], ['codigo_ibge'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades_saude', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_unidades_saude_regional_id'))
        batch_op.drop_index(batch_op.f('ix_unidades_saude_municipio_ibge'))
        batch_op.drop_column('regional_id')
        batch_op.drop_column('municipio_ibge')

    with op.batch_alter_table('municipios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipios_uf'))
        batch_op.drop_index(batch_op.f('ix_municipios_regional_id'))
        batch_op.drop_index(batch_op.f('ix_municipios_nome'))

    op.drop_table('municipios')
    # ### end Alembic commands ###
