"""Indices nas chaves estrangeiras

Revision ID: 95ac871bfcd4
Revises: d264aace5cce
Create Date: 2026-08-04 13:34:23.631514

O PostgreSQL indexa a chave primária, nunca a estrangeira. Sem índice, todo JOIN
por ela e toda checagem de integridade ao apagar o registro pai viram varredura
da tabela inteira. Eram 86 colunas nessa situação.

Duas ficaram especialmente caras depois do Row-Level Security: `unidade_id`
entrou na política de TODAS as tabelas clínicas, então passou a ser avaliada em
cada consulta do sistema — e estava sem índice na maioria delas. `paciente_id` é
o outro, por ser o eixo de praticamente todo JOIN clínico.

O custo é escrita: cada INSERT mantém mais um índice. Num prontuário, a
proporção leitura/escrita justifica com folga.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ac871bfcd4'
down_revision = 'd264aace5cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administracoes_med', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_administracoes_med_administrado_por'), ['administrado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_administracoes_med_item_prescricao_id'), ['item_prescricao_id'], unique=False)

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamentos_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atendimentos_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimentos_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimentos_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimentos_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('atendimentos_ps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atendimentos_ps_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimentos_ps_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimentos_ps_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimentos_ps_triagem_id'), ['triagem_id'], unique=False)

    with op.batch_alter_table('candidatos_duplicata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidatos_duplicata_decidido_por'), ['decidido_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidatos_duplicata_sobrevivente_id'), ['sobrevivente_id'], unique=False)

    with op.batch_alter_table('cirurgias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cirurgias_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_cirurgias_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cirurgias_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cirurgias_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cirurgias_sala_id'), ['sala_id'], unique=False)

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_atualizado_por'), ['atualizado_por'], unique=False)

    with op.batch_alter_table('consentimentos_lgpd', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consentimentos_lgpd_registrado_por'), ['registrado_por'], unique=False)

    with op.batch_alter_table('documentos_assinados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_assinados_assinado_por'), ['assinado_por'], unique=False)

    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encaminhamentos_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_encaminhamentos_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_encaminhamentos_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_encaminhamentos_prontuario_id'), ['prontuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_encaminhamentos_unidade_origem_id'), ['unidade_origem_id'], unique=False)

    with op.batch_alter_table('envios_rnds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_envios_rnds_criado_por'), ['criado_por'], unique=False)

    with op.batch_alter_table('evolucoes_internacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evolucoes_internacao_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolucoes_internacao_profissional_id'), ['profissional_id'], unique=False)

    with op.batch_alter_table('exames_solicitados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exames_solicitados_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_solicitados_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_solicitados_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_solicitados_prontuario_id'), ['prontuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_solicitados_tipo_exame_id'), ['tipo_exame_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exames_solicitados_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('faturamento_aih', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faturamento_aih_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_faturamento_aih_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faturamento_aih_medico_solicitante_id'), ['medico_solicitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faturamento_aih_paciente_id'), ['paciente_id'], unique=False)

    with op.batch_alter_table('faturamento_apac', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faturamento_apac_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_faturamento_apac_medico_solicitante_id'), ['medico_solicitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faturamento_apac_paciente_id'), ['paciente_id'], unique=False)

    with op.batch_alter_table('internacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internacoes_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_internacoes_leito_id'), ['leito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internacoes_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internacoes_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internacoes_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('itens_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_estoque_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('itens_prescricao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_prescricao_medicamento_id'), ['medicamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_prescricao_prescricao_id'), ['prescricao_id'], unique=False)

    with op.batch_alter_table('itens_prescricao_hosp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_prescricao_hosp_medicamento_id'), ['medicamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_prescricao_hosp_prescricao_id'), ['prescricao_id'], unique=False)

    with op.batch_alter_table('leitos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leitos_setor_id'), ['setor_id'], unique=False)

    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicos_unidade_id'), ['unidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicos_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('mov_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mov_estoque_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mov_estoque_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mov_estoque_unidade_id'), ['unidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mov_estoque_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('notificacoes_compulsorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_compulsorias_prontuario_id'), ['prontuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_compulsorias_resolvido_por'), ['resolvido_por'], unique=False)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_criado_por'), ['criado_por'], unique=False)

    with op.batch_alter_table('prescricoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescricoes_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_prontuario_id'), ['prontuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('prescricoes_hospitalares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescricoes_hospitalares_assinada_por'), ['assinada_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_hospitalares_criado_por'), ['criado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_hospitalares_internacao_id'), ['internacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_hospitalares_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_hospitalares_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescricoes_hospitalares_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('prontuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prontuarios_atendimento_id'), ['atendimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prontuarios_medico_id'), ['medico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prontuarios_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prontuarios_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('triagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triagens_agendamento_id'), ['agendamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triagens_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triagens_realizado_por'), ['realizado_por'], unique=False)
        batch_op.create_index(batch_op.f('ix_triagens_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_regional_id'), ['regional_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_unidade_id'), ['unidade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_users_regional_id'))

    with op.batch_alter_table('triagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triagens_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_triagens_realizado_por'))
        batch_op.drop_index(batch_op.f('ix_triagens_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_triagens_agendamento_id'))

    with op.batch_alter_table('prontuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prontuarios_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_prontuarios_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_prontuarios_medico_id'))
        batch_op.drop_index(batch_op.f('ix_prontuarios_atendimento_id'))

    with op.batch_alter_table('prescricoes_hospitalares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescricoes_hospitalares_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_hospitalares_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_hospitalares_medico_id'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_hospitalares_internacao_id'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_hospitalares_criado_por'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_hospitalares_assinada_por'))

    with op.batch_alter_table('prescricoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescricoes_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_prontuario_id'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_medico_id'))
        batch_op.drop_index(batch_op.f('ix_prescricoes_criado_por'))

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_criado_por'))

    with op.batch_alter_table('notificacoes_compulsorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_compulsorias_resolvido_por'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_compulsorias_prontuario_id'))

    with op.batch_alter_table('mov_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mov_estoque_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_mov_estoque_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_mov_estoque_item_id'))
        batch_op.drop_index(batch_op.f('ix_mov_estoque_internacao_id'))

    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicos_user_id'))
        batch_op.drop_index(batch_op.f('ix_medicos_unidade_id'))

    with op.batch_alter_table('leitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leitos_setor_id'))

    with op.batch_alter_table('itens_prescricao_hosp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_prescricao_hosp_prescricao_id'))
        batch_op.drop_index(batch_op.f('ix_itens_prescricao_hosp_medicamento_id'))

    with op.batch_alter_table('itens_prescricao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_prescricao_prescricao_id'))
        batch_op.drop_index(batch_op.f('ix_itens_prescricao_medicamento_id'))

    with op.batch_alter_table('itens_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_estoque_unidade_id'))

    with op.batch_alter_table('internacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internacoes_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_internacoes_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_internacoes_medico_id'))
        batch_op.drop_index(batch_op.f('ix_internacoes_leito_id'))
        batch_op.drop_index(batch_op.f('ix_internacoes_criado_por'))

    with op.batch_alter_table('faturamento_apac', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faturamento_apac_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_faturamento_apac_medico_solicitante_id'))
        batch_op.drop_index(batch_op.f('ix_faturamento_apac_criado_por'))

    with op.batch_alter_table('faturamento_aih', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faturamento_aih_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_faturamento_aih_medico_solicitante_id'))
        batch_op.drop_index(batch_op.f('ix_faturamento_aih_internacao_id'))
        batch_op.drop_index(batch_op.f('ix_faturamento_aih_criado_por'))

    with op.batch_alter_table('exames_solicitados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exames_solicitados_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_exames_solicitados_tipo_exame_id'))
        batch_op.drop_index(batch_op.f('ix_exames_solicitados_prontuario_id'))
        batch_op.drop_index(batch_op.f('ix_exames_solicitados_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_exames_solicitados_medico_id'))
        batch_op.drop_index(batch_op.f('ix_exames_solicitados_criado_por'))

    with op.batch_alter_table('evolucoes_internacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolucoes_internacao_profissional_id'))
        batch_op.drop_index(batch_op.f('ix_evolucoes_internacao_internacao_id'))

    with op.batch_alter_table('envios_rnds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_envios_rnds_criado_por'))

    with op.batch_alter_table('encaminhamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encaminhamentos_unidade_origem_id'))
        batch_op.drop_index(batch_op.f('ix_encaminhamentos_prontuario_id'))
        batch_op.drop_index(batch_op.f('ix_encaminhamentos_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_encaminhamentos_medico_id'))
        batch_op.drop_index(batch_op.f('ix_encaminhamentos_criado_por'))

    with op.batch_alter_table('documentos_assinados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_assinados_assinado_por'))

    with op.batch_alter_table('consentimentos_lgpd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consentimentos_lgpd_registrado_por'))

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_atualizado_por'))

    with op.batch_alter_table('cirurgias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cirurgias_sala_id'))
        batch_op.drop_index(batch_op.f('ix_cirurgias_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_cirurgias_medico_id'))
        batch_op.drop_index(batch_op.f('ix_cirurgias_internacao_id'))
        batch_op.drop_index(batch_op.f('ix_cirurgias_criado_por'))

    with op.batch_alter_table('candidatos_duplicata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidatos_duplicata_sobrevivente_id'))
        batch_op.drop_index(batch_op.f('ix_candidatos_duplicata_decidido_por'))

    with op.batch_alter_table('atendimentos_ps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atendimentos_ps_triagem_id'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_ps_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_ps_medico_id'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_ps_criado_por'))

    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atendimentos_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_medico_id'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_criado_por'))

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamentos_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_medico_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_criado_por'))

    with op.batch_alter_table('administracoes_med', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administracoes_med_item_prescricao_id'))
        batch_op.drop_index(batch_op.f('ix_administracoes_med_administrado_por'))

    # ### end Alembic commands ###
