"""Paridade SNPE: MFA, govbr, LGPD, RNDS, SINAN, configuracoes, hash-chain de auditoria

Revision ID: c08b950ed8fb
Revises: 
Create Date: 2026-07-29 20:45:27.596110

Migration inicial do schema, com paridade funcional ao monorepo NestJS+Next.

Alem das tabelas clinicas, traz o que o sistema precisa para ser um prontuario e
nao apenas um cadastro: segundo fator de autenticacao, login gov.br, registro de
consentimento LGPD, fila de envio a RNDS em FHIR, notificacao compulsoria ao
SINAN e — o mais importante — o encadeamento por hash da trilha de auditoria,
que torna o log resistente a alteracao sem depender de permissao do banco.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08b950ed8fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_nome', sa.String(length=160), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=False),
    sa.Column('hora', sa.String(length=5), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agenda_eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agenda_eventos_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_agenda_eventos_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_agenda_eventos_hora'), ['hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_agenda_eventos_paciente_nome'), ['paciente_nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_agenda_eventos_status'), ['status'], unique=False)

    op.create_table('catalogo_exames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('grupo', sa.String(length=80), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_exames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_exames_codigo'), ['codigo'], unique=True)

    op.create_table('catalogo_vacinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('doses', sa.String(length=80), nullable=True),
    sa.Column('faixa', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_vacinas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_vacinas_codigo'), ['codigo'], unique=True)

    op.create_table('medicamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_generico', sa.String(length=150), nullable=False),
    sa.Column('nome_comercial', sa.String(length=150), nullable=True),
    sa.Column('classe', sa.String(length=100), nullable=True),
    sa.Column('apresentacao', sa.String(length=100), nullable=True),
    sa.Column('via_admin', sa.String(length=50), nullable=True),
    sa.Column('controlado', sa.Boolean(), nullable=True),
    sa.Column('lista_rename', sa.String(length=10), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas_cirurgicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla', sa.String(length=10), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('andar', sa.String(length=10), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_exame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('unidades_saude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=140), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('cnes', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unidades_saude', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unidades_saude_cidade'), ['cidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_unidades_saude_cnes'), ['cnes'], unique=True)
        batch_op.create_index(batch_op.f('ix_unidades_saude_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_unidades_saude_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_unidades_saude_uf'), ['uf'], unique=False)

    op.create_table('vacinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('sigla', sa.String(length=50), nullable=True),
    sa.Column('doses_total', sa.Integer(), nullable=True),
    sa.Column('intervalo_dias', sa.Integer(), nullable=True),
    sa.Column('fabricante', sa.String(length=120), nullable=True),
    sa.Column('lote', sa.String(length=60), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('apresentacao', sa.String(length=100), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.Column('codigo_interno', sa.String(length=30), nullable=True),
    sa.Column('lote_atual', sa.String(length=30), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('estoque_minimo', sa.Float(), nullable=True),
    sa.Column('estoque_maximo', sa.Float(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['setor_id'], ['setores.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leitos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leitos_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('nivel_acesso', sa.String(length=20), nullable=False),
    sa.Column('regional_id', sa.Integer(), nullable=True),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_ativo', sa.Boolean(), nullable=False),
    sa.Column('mfa_confirmado_em', sa.DateTime(), nullable=True),
    sa.Column('govbr_sub', sa.String(length=120), nullable=True),
    sa.Column('govbr_nivel', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.ForeignKeyConstraint(['regional_id'], ['regionais.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_govbr_sub'), ['govbr_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_municipio_ibge'), ['municipio_ibge'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_uf'), ['uf'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela', sa.String(length=80), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('hash_anterior', sa.String(length=64), nullable=True),
    sa.Column('hash_atual', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_hash_atual'), ['hash_atual'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_registro_id'), ['registro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tabela'), ['tabela'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_chave'), ['chave'], unique=True)

    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crm', sa.String(length=20), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_social', sa.String(length=150), nullable=True),
    sa.Column('cns', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('raca_cor', sa.String(length=20), nullable=True),
    sa.Column('nome_mae', sa.String(length=150), nullable=True),
    sa.Column('nome_pai', sa.String(length=150), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('telefone2', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('tipo_sanguineo', sa.String(length=5), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cns'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_municipio_ibge'), ['municipio_ibge'], unique=False)

    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('motivo_cancel', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consentimentos_lgpd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('finalidade', sa.String(length=120), nullable=False),
    sa.Column('concedido', sa.Boolean(), nullable=False),
    sa.Column('base_legal', sa.String(length=80), nullable=True),
    sa.Column('versao_termo', sa.String(length=20), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('revogado_em', sa.DateTime(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consentimentos_lgpd', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consentimentos_lgpd_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('documentos_assinados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('referencia_tabela', sa.String(length=60), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=False),
    sa.Column('assinado_por', sa.Integer(), nullable=True),
    sa.Column('assinante_nome', sa.String(length=120), nullable=True),
    sa.Column('assinante_registro', sa.String(length=40), nullable=True),
    sa.Column('emitido_em', sa.DateTime(), nullable=False),
    sa.Column('revogado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_revogacao', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assinado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos_assinados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_assinados_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_documentos_assinados_emitido_em'), ['emitido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_assinados_hash_conteudo'), ['hash_conteudo'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_assinados_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('envios_rnds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('entidade_tabela', sa.String(length=60), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('protocolo', sa.String(length=80), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('envios_rnds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_envios_rnds_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_envios_rnds_entidade_id'), ['entidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_envios_rnds_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_envios_rnds_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_envios_rnds_tipo'), ['tipo'], unique=False)

    op.create_table('faturamento_apac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_solicitante_id', sa.Integer(), nullable=True),
    sa.Column('numero_apac', sa.String(length=20), nullable=True),
    sa.Column('procedimento_principal', sa.String(length=255), nullable=False),
    sa.Column('cid_principal', sa.String(length=10), nullable=True),
    sa.Column('data_inicio_validade', sa.Date(), nullable=False),
    sa.Column('data_fim_validade', sa.Date(), nullable=False),
    sa.Column('quantidade_aprovada', sa.Integer(), nullable=True),
    sa.Column('quantidade_realizada', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medico_solicitante_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_apac')
    )
    op.create_table('internacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('leito_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('hipotese_diag', sa.String(length=200), nullable=True),
    sa.Column('cid_principal', sa.String(length=10), nullable=True),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.Column('data_prevista_alta', sa.DateTime(), nullable=True),
    sa.Column('data_alta', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tipo_alta', sa.String(length=30), nullable=True),
    sa.Column('sumario_alta', sa.Text(), nullable=True),
    sa.Column('cid_alta', sa.String(length=10), nullable=True),
    sa.Column('aih_numero', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leito_id'], ['leitos.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacinas_aplicadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('vacina_id', sa.Integer(), nullable=True),
    sa.Column('nome_vacina', sa.String(length=120), nullable=True),
    sa.Column('dose', sa.String(length=40), nullable=True),
    sa.Column('data_aplicacao', sa.DateTime(), nullable=False),
    sa.Column('unidade', sa.String(length=120), nullable=True),
    sa.Column('profissional', sa.String(length=120), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['vacina_id'], ['vacinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacinas_aplicadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacinas_aplicadas_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacinas_aplicadas_vacina_id'), ['vacina_id'], unique=False)

    op.create_table('cirurgias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas_cirurgicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evolucoes_internacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('pressao_arterial', sa.String(length=10), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('frequencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frequencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('saturacao_o2', sa.Float(), nullable=True),
    sa.Column('diurese_ml', sa.Integer(), nullable=True),
    sa.Column('balanco_hidrico', sa.Integer(), nullable=True),
    sa.Column('subjetivo', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('avaliacao', sa.Text(), nullable=True),
    sa.Column('plano', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faturamento_aih',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('medico_solicitante_id', sa.Integer(), nullable=True),
    sa.Column('numero_aih', sa.String(length=20), nullable=True),
    sa.Column('procedimento_principal', sa.String(length=255), nullable=False),
    sa.Column('cid_principal', sa.String(length=10), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_apresentacao', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['medico_solicitante_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_aih')
    )
    op.create_table('mov_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('quantidade_anterior', sa.Float(), nullable=True),
    sa.Column('quantidade_posterior', sa.Float(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('lote', sa.String(length=30), nullable=True),
    sa.Column('fornecedor', sa.String(length=100), nullable=True),
    sa.Column('nota_fiscal', sa.String(length=50), nullable=True),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens_estoque.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescricoes_hospitalares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internacao_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('data_prescricao', sa.DateTime(), nullable=True),
    sa.Column('validade_horas', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['internacao_id'], ['internacoes.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prontuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('subjetivo', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('avaliacao', sa.Text(), nullable=True),
    sa.Column('plano', sa.Text(), nullable=True),
    sa.Column('pressao_arterial', sa.String(length=10), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('frequencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frequencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('saturacao_o2', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('glicemia', sa.Float(), nullable=True),
    sa.Column('cid_principal', sa.String(length=10), nullable=True),
    sa.Column('cid_secundario', sa.String(length=10), nullable=True),
    sa.Column('prescricao', sa.Text(), nullable=True),
    sa.Column('encaminhamento', sa.Text(), nullable=True),
    sa.Column('retorno_dias', sa.Integer(), nullable=True),
    sa.Column('assinado', sa.Boolean(), nullable=True),
    sa.Column('assinado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('realizado_por', sa.Integer(), nullable=True),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.Column('queixa_principal', sa.String(length=200), nullable=True),
    sa.Column('pressao_arterial', sa.String(length=10), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('frequencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frequencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('saturacao_o2', sa.Float(), nullable=True),
    sa.Column('glicemia', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('dor_escala', sa.Integer(), nullable=True),
    sa.Column('discriminadores', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['realizado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimentos_ps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('triagem_id', sa.Integer(), nullable=True),
    sa.Column('motivo_consulta', sa.Text(), nullable=False),
    sa.Column('diagnostico_preliminar', sa.Text(), nullable=True),
    sa.Column('conduta', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_chegada', sa.DateTime(), nullable=True),
    sa.Column('data_atendimento', sa.DateTime(), nullable=True),
    sa.Column('data_liberacao', sa.DateTime(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['triagem_id'], ['triagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encaminhamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('unidade_origem_id', sa.Integer(), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('servico_destino', sa.String(length=200), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('hipotese_diagnostica', sa.String(length=200), nullable=True),
    sa.Column('cid', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('data_realizacao', sa.DateTime(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('retorno_info', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.ForeignKeyConstraint(['unidade_origem_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exames_solicitados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('tipo_exame_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('urgencia', sa.String(length=10), nullable=True),
    sa.Column('indicacao_clinica', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('resultado_texto', sa.Text(), nullable=True),
    sa.Column('resultado_valor', sa.String(length=100), nullable=True),
    sa.Column('resultado_unidade', sa.String(length=30), nullable=True),
    sa.Column('valor_referencia', sa.String(length=100), nullable=True),
    sa.Column('interpretacao', sa.String(length=20), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_coleta', sa.DateTime(), nullable=True),
    sa.Column('data_resultado', sa.DateTime(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_exame_id'], ['tipos_exame.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_prescricao_hosp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescricao_hosp_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=True),
    sa.Column('nome_livre', sa.String(length=150), nullable=True),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('via', sa.String(length=50), nullable=True),
    sa.Column('frequencia', sa.String(length=100), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.ForeignKeyConstraint(['prescricao_hosp_id'], ['prescricoes_hospitalares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes_compulsorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('cid', sa.String(length=10), nullable=False),
    sa.Column('agravo', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('motivo_descarte', sa.String(length=255), nullable=True),
    sa.Column('numero_sinan', sa.String(length=30), nullable=True),
    sa.Column('detectado_em', sa.DateTime(), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.Column('resolvido_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.ForeignKeyConstraint(['resolvido_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacoes_compulsorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_compulsorias_cid'), ['cid'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_compulsorias_detectado_em'), ['detectado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_compulsorias_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_compulsorias_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_compulsorias_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('prescricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('validade_dias', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_saude.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administracoes_med',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_prescricao_id', sa.Integer(), nullable=False),
    sa.Column('administrado_por', sa.Integer(), nullable=True),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('data_administracao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['administrado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_prescricao_id'], ['itens_prescricao_hosp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_prescricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescricao_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=True),
    sa.Column('nome_livre', sa.String(length=150), nullable=True),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('via', sa.String(length=50), nullable=True),
    sa.Column('frequencia', sa.String(length=100), nullable=True),
    sa.Column('duracao', sa.String(length=100), nullable=True),
    sa.Column('quantidade', sa.String(length=50), nullable=True),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.id'], ),
    sa.ForeignKeyConstraint(['prescricao_id'], ['prescricoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_prescricao')
    op.drop_table('administracoes_med')
    op.drop_table('prescricoes')
    with op.batch_alter_table('notificacoes_compulsorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_compulsorias_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_compulsorias_status'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_compulsorias_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_compulsorias_detectado_em'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_compulsorias_cid'))

    op.drop_table('notificacoes_compulsorias')
    op.drop_table('itens_prescricao_hosp')
    op.drop_table('exames_solicitados')
    op.drop_table('encaminhamentos')
    op.drop_table('atendimentos_ps')
    op.drop_table('triagens')
    op.drop_table('prontuarios')
    op.drop_table('prescricoes_hospitalares')
    op.drop_table('mov_estoque')
    op.drop_table('faturamento_aih')
    op.drop_table('evolucoes_internacao')
    op.drop_table('cirurgias')
    with op.batch_alter_table('vacinas_aplicadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacinas_aplicadas_vacina_id'))
        batch_op.drop_index(batch_op.f('ix_vacinas_aplicadas_paciente_id'))

    op.drop_table('vacinas_aplicadas')
    op.drop_table('internacoes')
    op.drop_table('faturamento_apac')
    with op.batch_alter_table('envios_rnds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_envios_rnds_tipo'))
        batch_op.drop_index(batch_op.f('ix_envios_rnds_status'))
        batch_op.drop_index(batch_op.f('ix_envios_rnds_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_envios_rnds_entidade_id'))
        batch_op.drop_index(batch_op.f('ix_envios_rnds_criado_em'))

    op.drop_table('envios_rnds')
    with op.batch_alter_table('documentos_assinados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_assinados_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_assinados_hash_conteudo'))
        batch_op.drop_index(batch_op.f('ix_documentos_assinados_emitido_em'))
        batch_op.drop_index(batch_op.f('ix_documentos_assinados_codigo'))

    op.drop_table('documentos_assinados')
    with op.batch_alter_table('consentimentos_lgpd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consentimentos_lgpd_paciente_id'))

    op.drop_table('consentimentos_lgpd')
    op.drop_table('atendimentos')
    op.drop_table('agendamentos')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_municipio_ibge'))

    op.drop_table('pacientes')
    op.drop_table('medicos')
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_chave'))

    op.drop_table('configuracoes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tabela'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_registro_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_hash_atual'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_criado_em'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_acao'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uf'))
        batch_op.drop_index(batch_op.f('ix_users_municipio_ibge'))
        batch_op.drop_index(batch_op.f('ix_users_govbr_sub'))
        batch_op.drop_index(batch_op.f('ix_users_cpf'))

    op.drop_table('users')
    with op.batch_alter_table('leitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leitos_unidade_id'))

    op.drop_table('leitos')
    op.drop_table('itens_estoque')
    op.drop_table('vacinas')
    with op.batch_alter_table('unidades_saude', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidades_saude_uf'))
        batch_op.drop_index(batch_op.f('ix_unidades_saude_tipo'))
        batch_op.drop_index(batch_op.f('ix_unidades_saude_nome'))
        batch_op.drop_index(batch_op.f('ix_unidades_saude_cnes'))
        batch_op.drop_index(batch_op.f('ix_unidades_saude_cidade'))

    op.drop_table('unidades_saude')
    op.drop_table('tipos_exame')
    op.drop_table('setores')
    op.drop_table('salas_cirurgicas')
    op.drop_table('regionais')
    op.drop_table('medicamentos')
    with op.batch_alter_table('catalogo_vacinas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_vacinas_codigo'))

    op.drop_table('catalogo_vacinas')
    with op.batch_alter_table('catalogo_exames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_exames_codigo'))

    op.drop_table('catalogo_exames')
    with op.batch_alter_table('agenda_eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agenda_eventos_status'))
        batch_op.drop_index(batch_op.f('ix_agenda_eventos_paciente_nome'))
        batch_op.drop_index(batch_op.f('ix_agenda_eventos_hora'))
        batch_op.drop_index(batch_op.f('ix_agenda_eventos_data'))
        batch_op.drop_index(batch_op.f('ix_agenda_eventos_ativo'))

    op.drop_table('agenda_eventos')
    # ### end Alembic commands ###
