"""Fila RNDS: idempotencia e agendamento de retentativa

Revision ID: cad0b85b049d
Revises: b01e62a90ec6
Create Date: 2026-08-03 20:42:18.091337

O envio à RNDS deixou de acontecer dentro da requisição e passou a ser uma fila
durável. Isso exige duas colunas: a impressão digital do conteúdo, que impede o
mesmo documento de entrar duas vezes, e o instante da próxima tentativa, que
sustenta o recuo exponencial.

"""
import hashlib

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad0b85b049d'
down_revision = 'b01e62a90ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envios_rnds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_idempotencia', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('proxima_tentativa', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_envios_rnds_chave_idempotencia'), ['chave_idempotencia'], unique=True)
        batch_op.create_index(batch_op.f('ix_envios_rnds_proxima_tentativa'), ['proxima_tentativa'], unique=False)

    _preencher_chaves()


def _preencher_chaves():
    """Calcula a chave dos envios já gravados.

    Sem isto, todo registro anterior fica com chave nula e escapa da
    deduplicação. O payload antigo não era serializado com chaves ordenadas, e
    por isso a chave calculada aqui pode não coincidir com a de um documento
    idêntico enfileirado depois — o que custa, no pior caso, uma linha repetida
    uma única vez. Colisão entre linhas antigas é resolvida deixando a segunda
    sem chave, já que o índice é único.
    """
    conexao = op.get_bind()
    linhas = conexao.execute(sa.text(
        "SELECT id, tipo, entidade_tabela, entidade_id, payload "
        "FROM envios_rnds WHERE payload IS NOT NULL"
    )).fetchall()

    vistas = set()
    for id_, tipo, tabela, entidade_id, payload in linhas:
        bruto = f"{tipo}|{tabela}|{entidade_id}|{payload}"
        chave = hashlib.sha256(bruto.encode("utf-8")).hexdigest()
        if chave in vistas:
            continue
        vistas.add(chave)
        conexao.execute(
            sa.text("UPDATE envios_rnds SET chave_idempotencia = :c WHERE id = :i"),
            {"c": chave, "i": id_},
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envios_rnds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_envios_rnds_proxima_tentativa'))
        batch_op.drop_index(batch_op.f('ix_envios_rnds_chave_idempotencia'))
        batch_op.drop_column('proxima_tentativa')
        batch_op.drop_column('chave_idempotencia')

    # ### end Alembic commands ###
